import type { ToolConfig } from '@/types/tool';
import type { ComponentType } from 'react';

/**
 * Auto-registry of tools using Vite's import.meta.glob.
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * Adding a new tool:
 * 1. Create a folder in src/tools/[tool-id]/
 * 2. Export a config.ts with a ToolConfig
 * 3. Export an index.tsx with a default React component
 * The registry will pick it up automatically.
 */

// Eagerly load all tool configs
const configModules = import.meta.glob<{ config: ToolConfig }>('./*/config.ts', { eager: true });

// Lazily load tool components
const toolModules = import.meta.glob<{ default: ComponentType }>('./*/index.tsx');

/**
 * Get all registered tool configs.
 */
export function getAllTools(): ToolConfig[] {
  return Object.values(configModules).map((mod) => mod.config);
}

/**
 * Get a specific tool config by ID.
 */
export function getToolConfig(id: string): ToolConfig | undefined {
  return getAllTools().find((tool) => tool.id === id);
}

/**
 * Dynamically load a tool component by ID.
 */
export async function loadTool(id: string): Promise<ComponentType | null> {
  const entry = Object.entries(toolModules).find(([path]) => path.includes(`/${id}/`));

  if (!entry) return null;

  const mod = await entry[1]();
  return mod.default;
}

/**
 * Get all tool IDs (used for static path generation).
 */
export function getAllToolIds(): string[] {
  return getAllTools().map((tool) => tool.id);
}
